"""WebSocket event type constants."""


class WsEvent:
    # Session
    SESSION_ASSIGNED = "SESSION_ASSIGNED"
    ROBOT_APPROACHING = "ROBOT_APPROACHING"
    PIN_MATCHING = "PIN_MATCHING"
    SESSION_ACTIVE = "SESSION_ACTIVE"
    SESSION_ENDED = "SESSION_ENDED"

    # Guide
    GUIDE_QUEUE_UPDATED = "GUIDE_QUEUE_UPDATED"
    GUIDE_NAVIGATING = "GUIDE_NAVIGATING"
    GUIDE_ARRIVED = "GUIDE_ARRIVED"

    # Follow
    FOLLOW_STARTED = "FOLLOW_STARTED"
    FOLLOW_STATUS = "FOLLOW_STATUS"
    FOLLOW_STOPPED = "FOLLOW_STOPPED"

    # Pickup
    PICKUP_STATUS_CHANGED = "PICKUP_STATUS_CHANGED"
    PICKUP_MEET_SET = "PICKUP_MEET_SET"

    # Lockbox
    LOCKBOX_UPDATED = "LOCKBOX_UPDATED"
    LOCKBOX_OPENED = "LOCKBOX_OPENED"

    # Robot
    ROBOT_STATE_UPDATED = "ROBOT_STATE_UPDATED"
    ROBOT_ESTOP = "ROBOT_ESTOP"
    ROBOT_ESTOP_RELEASED = "ROBOT_ESTOP_RELEASED"
    ROBOT_EVENT = "ROBOT_EVENT"

    # Mission
    MISSION_CREATED = "MISSION_CREATED"
    MISSION_UPDATED = "MISSION_UPDATED"

    # System
    PONG = "PONG"
